### ISSUE TITLE
Makes current node as seed node

### ISSUE THREAD

**Issue by tanroopdhillon** [oscerd/docker-cassandra#6]
SEED=${SEED:=$ADDR}
 The above line makes current node as seed node.

Getting the below line in logs
This node will not auto bootstrap because it is configured to be a seed node

I am not able to add new nodes in the cluster. No handshaking is observed.

**Comment by oscerd** [comment]
It's not really clear. What logs? What line from what folder? Please be a bit more specific

**Comment by oscerd** [comment]
What version too

**Comment by tanroopdhillon** [comment]
I am using 2.0.7. I have to upgrade to 3.x from this version on prod.

Basically, nodes are not becoming part of cluster.
In the docker logs, I can see the below mentioned line
`This node will not auto bootstrap because it is configured to be a seed node`.

Is the parameter `SEED` getting honoured / used ?

**Comment by tanroopdhillon** [comment]
I had made some changes in my docker commands. 

Used the exactly same ones you've mentioned. I can see the nodes becoming part of the cluster.

My bad. The issue is resolved now. 

Thanks :)
